// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skyqyzhscibmrduagzjc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNreXF5emhzY2libXJkdWFnempjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4Nzg0MzEsImV4cCI6MjA4NzQ1NDQzMX0.WfGEfSW67OLb1Pa9w8fdkBt2mDdaQLvM2Kraggqa84k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});